### PR TITLE
Added configuration options

### PR DESCRIPTION
**Pull request by pbringetto**
When searching large tables to only confirm whether matches exist, removing sorting and relevance checking will significantly increase query performance. To adjust the relevance threshold you can filter the relevance data Manually

```php
DB::table('users')
  ->whereFuzzy('name', 'jd', false) 
  ->orWhereFuzzy('name', 'gm', 0, false);
  ->first();
```

When searching large tables, removing matchers will significantly increase query performance.

```php
DB::table('users')
  ->whereFuzzy('name', 'jd', true, [
    'AcronymMatcher',
    'StudlyCaseMatcher',
  ]);
  ->first();
```
#### Matchers
- ExactMatcher
- StartOfStringMatcher
- AcronymMatcher
- ConsecutiveCharactersMatcher
- StartOfWordsMatcher
- StudlyCaseMatcher
- InStringMatcher
- TimesInStringMatcher

### CODE REVIEW

**Comment by mattkingshott** [comment]
I'm not opposed to this, but a few things:

1. The docs need to be updated to reference the presence of the config file, publishing it, as well as when you'd want to publish it.
2. The config file needs explanations for each of the options (just like in a Laravel config file).
3. Instead of using if statements, use the query builder's `when` method to keep the query fluent.
4. Tests are failing.

**Comment by mattkingshott** [comment]
After thinking on this some more, I’m wondering whether it makes sense to offer a more flexible option to control whether you want to do this on a particular query (or more likely whether you want to turn it off for a query). 

Do you feel this is something that should be more flexible than a global config value?

**Comment by pbringetto** [comment]
> After thinking on this some more, I’m wondering whether it makes sense to offer a more flexible option to control whether you want to do this on a particular query (or more likely whether you want to turn it off for a query).
> 
> Do you feel this is something that should be more flexible than a global config value?

That makes sense and an easy update.

**Comment by pbringetto** [comment]
I added another param to disable individual matchers to increase performance.

**Comment by mattkingshott** [comment]
This looks great! Thanks, I'll just update the docs a little and tag a new version 👍🏻

**Comment by mattkingshott** [comment]
Available in v4.0.0

**Pull request merged**
